name: Deploy to EC2

on:
  push:
    branches:
      - main  # main 브랜치에 push되면 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Connect & Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/kdt5-3rd-back
            git pull origin main
            npm install
            npx tsc
            pm2 restart tgb
